services:
  postgres:
    image: postgres:latest
    container_name: parametros_db
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}  
      POSTGRES_DB: ${DB_POSTGRES}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_POSTGRES} -d parametrosdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
